# -*- coding: utf-8 -*-
"""Infosys Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15D30qTBwUf-qQdTT9Zqp16JrpOzl1_td
"""

from abc import ABC, abstractmethod

class Memory:
    def __init__(self):
        self._storage = []

    def store(self, item):
        self._storage.append(item)

    def retrieve(self):
        return list(self._storage)

    def clear(self):
        self._storage.clear()


class Tool(ABC):
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def use(self, *args, **kwargs):
        pass


class SearchTool(Tool):
    def __init__(self):
        super().__init__(name="SearchTool")

    def use(self, text: str, keyword: str) -> str:
        lines = text.splitlines()
        matches = [line for line in lines if keyword.lower() in line.lower()]
        if not matches:
            return f"[SearchTool] No matches found for '{keyword}'."
        result = "[SearchTool] Found matches:\n" + "\n".join(matches)
        return result


class SummaryTool(Tool):
    def __init__(self, max_sentences: int = 2):
        super().__init__(name="SummaryTool")
        self.max_sentences = max_sentences

    def use(self, text: str) -> str:
        sentences = [s.strip() for s in text.split(".") if s.strip()]
        if not sentences:
            return "[SummaryTool] Nothing to summarize."
        summary = ". ".join(sentences[:self.max_sentences])
        return f"[SummaryTool] Summary: {summary}."


class Agent:
    def __init__(self, name: str, role: str, memory: Memory, tools: dict):
        self.name = name
        self.role = role
        self.memory = memory
        self.tools = tools

    def think(self, input_text: str) -> str:
        text_lower = input_text.lower()
        if "search:" in text_lower:
            return "use_search_tool"
        elif "summary" in text_lower or "summarize" in text_lower:
            return "use_summary_tool"
        else:
            return "just_store"

    def act(self, plan: str, input_text: str) -> str:
        if plan == "use_search_tool":
            try:
                _, rest = input_text.split("search:", 1)
                keyword_part, text_part = rest.split("|", 1)
                keyword = keyword_part.strip()
                text_to_search = text_part.strip()
                tool = self.tools.get("search")
                if tool is None:
                    return "[Agent] Search tool not available."
                result = tool.use(text_to_search, keyword)
                self.memory.store({"action": "search", "keyword": keyword, "result": result})
                return result
            except ValueError:
                return "[Agent] Invalid format for search. Use: 'search: <keyword> | <text>'"
        elif plan == "use_summary_tool":
            tool = self.tools.get("summary")
            if tool is None:
                return "[Agent] Summary tool not available."
            result = tool.use(input_text)
            self.memory.store({"action": "summary", "result": result})
            return result
        else:
            self.memory.store({"action": "store_only", "text": input_text})
            return "[Agent] Stored your input in memory."

    def run(self, input_text: str) -> str:
        self.memory.store({"action": "raw_input", "text": input_text})
        plan = self.think(input_text)
        result = self.act(plan, input_text)
        return result


if __name__ == "__main__":
    memory = Memory()
    tools = {
        "search": SearchTool(),
        "summary": SummaryTool(max_sentences=2),
    }

    agent = Agent(
        name="DemoAgent",
        role="Helpful Assistant",
        memory=memory,
        tools=tools,
    )

    print(agent.run("This is a random note that the agent should remember."))

    long_text = (
        "Machine learning is a field of AI that uses data to learn patterns. "
        "It powers many modern applications. "
        "It is widely used in recommendation systems and computer vision."
    )
    print(agent.run("Please summarize this: " + long_text))

    search_input = (
        "search: python | "
        "Python is a popular programming language.\n"
        "Many people also use Java.\n"
        "Python is great for data science."
    )
    print(agent.run(search_input))

    print("\n=== Agent Memory ===")
    for item in memory.retrieve():
        print(item)

